In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.3'

In [3]:
data=pd.read_csv("car_fuel_efficiency_2026.csv")

In [4]:
data.shape

(10000, 11)

In [5]:
data["fuel_type"].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [6]:
data.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [7]:
data.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [8]:
data["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [9]:
data['horsepower'].median()

np.float64(254.0)

In [10]:
data['horsepower'].mode()[0]

np.float64(252.0)

In [11]:
data[data["origin"]=="Asia"]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [12]:
data.loc[:,["vehicle_weight","model_year"]]

      vehicle_weight  model_year
0               3870        2006
1               4210        2008
2               4240        1996
3               4490        1989
4               4510        1994
...              ...         ...
9995            4690        2005
9996            4370        1993
9997            4590        2014
9998            4450        2004
9999            4370        2011

[10000 rows x 2 columns]

In [13]:
data=data.loc[0:6,["vehicle_weight","model_year"]]

In [14]:
X=data.to_numpy()
X.shape

(7, 2)

In [15]:
XTX=X.T @ X
XTX

array([[127902500,  59738830],
       [ 59738830,  27968386]])

In [16]:
XTX=np.matmul(X.T,X)

In [17]:
XTX_inv=np.linalg.inv(XTX)

In [18]:
y=np.array([1100,1300,800,900,1000, 1100, 1200])

In [19]:
w=XTX_inv @( X.T @ y)

In [20]:
w.sum()

np.float64(0.7996290105453303)